import { Router, type IRouter } from "express";
import { z } from "zod";

const router: IRouter = Router();

const holidayPackages = [
  {
    id: "HOL001",
    title: "Magical Goa Beach Escape",
    destination: "Goa",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&h=600&fit=crop",
    duration: "4 Nights / 5 Days",
    startingPrice: 14999,
    originalPrice: 19999,
    discount: 25,
    rating: 4.6,
    reviewCount: 1243,
    category: "Beach",
    highlights: ["North & South Goa Sightseeing", "Dudhsagar Waterfalls Trip", "Sunset Cruise on Mandovi River", "Water Sports Package"],
    inclusions: ["Return flights from Delhi", "4-star hotel stay", "Daily breakfast & dinner", "AC cab transfers", "Travel insurance"],
    exclusions: ["Personal expenses", "Lunch", "Optional activities", "Visa fees"],
    itinerary: [
      { day: 1, title: "Arrival in Goa", description: "Pick up from Goa airport, check-in to hotel. Evening at leisure on Calangute Beach." },
      { day: 2, title: "North Goa Tour", description: "Fort Aguada, Baga Beach, Anjuna Flea Market, Vagator Beach. Evening Sunset Cruise." },
      { day: 3, title: "Dudhsagar Waterfall", description: "Full day trip to the stunning Dudhsagar Falls through Mollem National Park." },
      { day: 4, title: "South Goa Tour", description: "Colva Beach, Palolem Beach, Cabo de Rama Fort. Water sports at Benaulim beach." },
      { day: 5, title: "Departure", description: "Breakfast at hotel, check-out and transfer to Goa airport for return flight." },
    ],
    departureCity: "Delhi",
    departureDate: "2026-05-01",
    availableSeats: 12,
    tags: ["Beach", "Family", "Couples", "Budget Friendly"],
  },
  {
    id: "HOL002",
    title: "Kerala Backwaters & Ayurveda Retreat",
    destination: "Kerala",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&h=600&fit=crop",
    duration: "5 Nights / 6 Days",
    startingPrice: 22999,
    originalPrice: 28999,
    discount: 20,
    rating: 4.8,
    reviewCount: 876,
    category: "Nature & Wellness",
    highlights: ["Alleppey Houseboat Stay", "Munnar Tea Gardens", "Ayurvedic Spa Treatment", "Kathakali Dance Show"],
    inclusions: ["Return flights from Mumbai", "Hotel + houseboat stays", "All meals on houseboat", "AC cab transfers", "Ayurvedic consultation"],
    exclusions: ["Personal expenses", "Optional excursions", "Travel insurance"],
    itinerary: [
      { day: 1, title: "Arrive Kochi", description: "Kochi airport pickup, Fort Kochi sightseeing, Chinese fishing nets, Kathakali show." },
      { day: 2, title: "Kochi to Munnar", description: "Drive through scenic tea gardens, Eravikulam National Park, Mattupetty Dam." },
      { day: 3, title: "Munnar Tea Trails", description: "Tea museum visit, trekking through tea estates, Atukkad Waterfalls." },
      { day: 4, title: "Munnar to Alleppey", description: "Morning Ayurvedic treatment, drive to Alleppey, board the luxury houseboat." },
      { day: 5, title: "Backwater Cruise", description: "Full day houseboat cruise through Alleppey backwaters, village visits." },
      { day: 6, title: "Departure", description: "Transfer to Kochi airport for return flight home." },
    ],
    departureCity: "Mumbai",
    departureDate: "2026-05-10",
    availableSeats: 8,
    tags: ["Nature", "Wellness", "Couples", "Honeymoon"],
  },
  {
    id: "HOL003",
    title: "Royal Rajasthan Heritage Tour",
    destination: "Rajasthan",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&h=600&fit=crop",
    duration: "6 Nights / 7 Days",
    startingPrice: 29999,
    originalPrice: 35999,
    discount: 16,
    rating: 4.7,
    reviewCount: 1087,
    category: "Heritage & Culture",
    highlights: ["Jaipur Pink City Tour", "Udaipur Lake Palace Visit", "Jodhpur Blue City", "Camel Safari in Jaisalmer"],
    inclusions: ["Return flights from Bangalore", "Heritage hotel stays", "Daily breakfast", "AC cab transfers", "Monument entry fees"],
    exclusions: ["Lunch & dinner", "Shopping", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrive Jaipur", description: "Transfer to heritage hotel. Evening at Chokhi Dhani for cultural program." },
      { day: 2, title: "Jaipur Sightseeing", description: "Amber Fort, City Palace, Jantar Mantar, Hawa Mahal and local bazaars." },
      { day: 3, title: "Jaipur to Jodhpur", description: "Drive to the Blue City. Mehrangarh Fort, Jaswant Thada, blue lanes tour." },
      { day: 4, title: "Jodhpur to Udaipur", description: "En route visit Ranakpur Jain Temples. Check-in to lake-view hotel in Udaipur." },
      { day: 5, title: "Udaipur Lakes", description: "City Palace, Lake Pichola boat ride, Saheliyon Ki Bari, Vintage Car Museum." },
      { day: 6, title: "Udaipur to Jaisalmer", description: "Flight to Jaisalmer. Jaisalmer Fort, Patwon Ki Haveli, Sam Sand Dunes camel safari." },
      { day: 7, title: "Departure", description: "Jaisalmer local market, transfer to Jodhpur airport for flight home." },
    ],
    departureCity: "Bangalore",
    departureDate: "2026-04-20",
    availableSeats: 15,
    tags: ["Heritage", "Culture", "Family", "Adventure"],
  },
  {
    id: "HOL004",
    title: "Bali Bliss - Island Paradise",
    destination: "Bali",
    country: "Indonesia",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop",
    duration: "5 Nights / 6 Days",
    startingPrice: 44999,
    originalPrice: 55999,
    discount: 19,
    rating: 4.9,
    reviewCount: 2134,
    category: "International",
    highlights: ["Uluwatu Temple Sunset", "Tegallalang Rice Terraces", "Mount Batur Sunrise Trek", "Ubud Art & Culture Tour"],
    inclusions: ["Return international flights", "5-star villa stay", "Daily breakfast", "Airport transfers", "Cooking class"],
    exclusions: ["Visa on arrival (USD 35)", "Travel insurance", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrive Bali", description: "Ngurah Rai airport pickup, villa check-in. Seminyak beach sunset." },
      { day: 2, title: "Uluwatu & Kuta", description: "Uluwatu cliff temple, Kecak fire dance, Kuta beach." },
      { day: 3, title: "Ubud Cultural Day", description: "Tegallalang rice terraces, Ubud monkey forest, art galleries, cooking class." },
      { day: 4, title: "Mount Batur Sunrise", description: "4 AM trek to Mount Batur for sunrise. Afternoon hot springs and spa." },
      { day: 5, title: "Nusa Penida Day Trip", description: "Speedboat to Nusa Penida, Kelingking Beach, Angel's Billabong, snorkeling." },
      { day: 6, title: "Departure", description: "Tanah Lot temple visit, shopping at Seminyak boutiques, airport transfer." },
    ],
    departureCity: "Mumbai",
    departureDate: "2026-06-01",
    availableSeats: 6,
    tags: ["International", "Honeymoon", "Beach", "Adventure"],
  },
  {
    id: "HOL005",
    title: "Himalayan Manali Adventure",
    destination: "Manali",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=600&fit=crop",
    duration: "4 Nights / 5 Days",
    startingPrice: 12999,
    originalPrice: 15999,
    discount: 18,
    rating: 4.5,
    reviewCount: 943,
    category: "Adventure",
    highlights: ["Rohtang Pass Snow Point", "Solang Valley Skiing", "Hadimba Devi Temple", "River Rafting in Beas"],
    inclusions: ["Volvo AC bus from Delhi", "Hotel stay on twin sharing", "Daily breakfast & dinner", "Local sightseeing by cab"],
    exclusions: ["Rohtang Pass permit", "Adventure sports charges", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Delhi to Manali", description: "Overnight Volvo bus journey from Delhi to Manali." },
      { day: 2, title: "Arrive Manali", description: "Hotel check-in, rest. Evening visit Mall Road, Hadimba temple, Old Manali." },
      { day: 3, title: "Solang Valley", description: "Solang Valley snow point, skiing, zorbing, paragliding. Evening bonfire." },
      { day: 4, title: "Rohtang Pass", description: "Early morning trip to Rohtang Pass (subject to permit). Beas River rafting." },
      { day: 5, title: "Return to Delhi", description: "Manali sightseeing - Vashisht Temple, Van Vihar. Evening bus to Delhi." },
    ],
    departureCity: "Delhi",
    departureDate: "2026-05-15",
    availableSeats: 20,
    tags: ["Adventure", "Snow", "Trekking", "Youth"],
  },
  {
    id: "HOL006",
    title: "Dubai Glam & Desert Safari",
    destination: "Dubai",
    country: "UAE",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop",
    duration: "4 Nights / 5 Days",
    startingPrice: 54999,
    originalPrice: 65999,
    discount: 16,
    rating: 4.8,
    reviewCount: 1567,
    category: "International",
    highlights: ["Burj Khalifa Observation Deck", "Desert Safari with BBQ Dinner", "Dubai Mall & Fountain Show", "Dhow Cruise Dinner"],
    inclusions: ["Return international flights", "5-star hotel stay", "Daily breakfast", "Airport transfers", "Dubai tourist visa"],
    exclusions: ["Lunch & dinner (except included)", "Shopping", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrive Dubai", description: "Airport pickup, hotel check-in. Dubai Mall, Fountain Show, Burj Khalifa." },
      { day: 2, title: "City Tour", description: "Old Dubai - Gold Souk, Spice Souk, Abra boat ride. Jumeirah Mosque, Palm." },
      { day: 3, title: "Desert Safari", description: "Full-day desert safari with dune bashing, camel riding, BBQ dinner, Tanoura dance." },
      { day: 4, title: "Theme Parks / Leisure", description: "Dubai Frame, IMG Worlds of Adventure or free day for shopping at Mall of Emirates." },
      { day: 5, title: "Departure", description: "Last minute shopping at Duty Free, transfer to Dubai International Airport." },
    ],
    departureCity: "Delhi",
    departureDate: "2026-04-25",
    availableSeats: 10,
    tags: ["International", "Luxury", "Shopping", "Family"],
  },
  {
    id: "HOL007",
    title: "Andaman Island Retreat",
    destination: "Andaman",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
    duration: "5 Nights / 6 Days",
    startingPrice: 26999,
    originalPrice: 32999,
    discount: 18,
    rating: 4.7,
    reviewCount: 734,
    category: "Beach & Island",
    highlights: ["Radhanagar Beach (Asia's Best)", "Scuba Diving at Neil Island", "Cellular Jail Light & Sound Show", "Sea Walk Experience"],
    inclusions: ["Return flights from Kolkata", "Beachside resort stay", "Daily breakfast & dinner", "Inter-island ferry tickets", "Snorkeling equipment"],
    exclusions: ["Scuba diving charges", "Optional activities", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrive Port Blair", description: "Airport pickup, Cellular Jail tour and evening light & sound show." },
      { day: 2, title: "Havelock Island", description: "Ferry to Havelock. Radhanagar Beach (Asia's Best Beach), sunset watching." },
      { day: 3, title: "Water Adventures", description: "Snorkeling at Elephant Beach, sea walk, glass-bottom boat ride." },
      { day: 4, title: "Neil Island", description: "Ferry to Neil Island. Natural bridge, Laxmanpur Beach, scuba diving." },
      { day: 5, title: "Return Port Blair", description: "Return ferry. North Bay Island coral garden, Ross Island historical tour." },
      { day: 6, title: "Departure", description: "Breakfast and transfer to Port Blair airport for return flight." },
    ],
    departureCity: "Kolkata",
    departureDate: "2026-05-20",
    availableSeats: 14,
    tags: ["Beach", "Island", "Water Sports", "Nature"],
  },
  {
    id: "HOL008",
    title: "Singapore & Universal Studios",
    destination: "Singapore",
    country: "Singapore",
    imageUrl: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop",
    duration: "4 Nights / 5 Days",
    startingPrice: 58999,
    originalPrice: 72999,
    discount: 19,
    rating: 4.8,
    reviewCount: 1892,
    category: "International",
    highlights: ["Universal Studios Singapore", "Gardens by the Bay", "Sentosa Island Full Day", "Night Safari Experience"],
    inclusions: ["Return international flights", "4-star hotel in Orchard Road", "Daily breakfast", "Airport transfers", "Singapore visa"],
    exclusions: ["Lunch & dinner", "Theme park tickets (unless specified)", "Personal expenses"],
    itinerary: [
      { day: 1, title: "Arrive Singapore", description: "Changi Airport pickup, hotel check-in. Orchard Road, Marina Bay Sands." },
      { day: 2, title: "Universal Studios", description: "Full day at Universal Studios Sentosa. Evening S.E.A. Aquarium." },
      { day: 3, title: "City Exploration", description: "Gardens by the Bay, Merlion Park, Chinatown, Little India, Clarke Quay." },
      { day: 4, title: "Night Safari & Sentosa", description: "Afternoon Sentosa beach. Evening Singapore Night Safari." },
      { day: 5, title: "Departure", description: "Jewel Changi waterfall visit, last-minute duty free shopping, departure." },
    ],
    departureCity: "Chennai",
    departureDate: "2026-06-10",
    availableSeats: 9,
    tags: ["International", "Family", "Theme Parks", "Shopping"],
  },
];

const HolidayPackagesResponse = z.array(z.object({
  id: z.string(),
  title: z.string(),
  destination: z.string(),
  country: z.string(),
  imageUrl: z.string(),
  duration: z.string(),
  startingPrice: z.number(),
  originalPrice: z.number(),
  discount: z.number(),
  rating: z.number(),
  reviewCount: z.number(),
  category: z.string(),
  highlights: z.array(z.string()),
  inclusions: z.array(z.string()),
  exclusions: z.array(z.string()),
  itinerary: z.array(z.object({ day: z.number(), title: z.string(), description: z.string() })),
  departureCity: z.string(),
  departureDate: z.string(),
  availableSeats: z.number(),
  tags: z.array(z.string()),
}));

router.get("/", (req, res) => {
  let packages = holidayPackages;
  const { destination, category } = req.query as { destination?: string; category?: string };
  if (destination) {
    packages = packages.filter(p =>
      p.destination.toLowerCase().includes(destination.toLowerCase()) ||
      p.country.toLowerCase().includes(destination.toLowerCase())
    );
  }
  if (category) {
    packages = packages.filter(p => p.category.toLowerCase().includes(category.toLowerCase()));
  }
  const data = HolidayPackagesResponse.parse(packages);
  res.json(data);
});

export default router;
